ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace KitKat.ViewModels
{
    public class LoginViewModel
    {
        [Required]
        public string UserName { get; set; }

        [Required]
        public string Password { get; set; }
    }
}

ViewModels/RoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace KitKat.ViewModels
{
    public class RoleViewModel
    {
        [Required]
        [StringLength(50,MinimumLength =3)]
        public string RoleName { get; set; }
    }
}

Controllers/Api/RolesController.cs
using AutoMapper;
using KitKat.Data.Contracts;
using KitKat.Models;
using KitKat.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace  KitKat.Controllers.Api
{
    [Route("api/roles")]
    [Authorize]
    public class RolesController:Controller
    {
        private ILogger<RolesController> _logger;
        private IRoleRepository _repository;

        public RolesController(IRoleRepository repository,ILogger<RolesController> logger)
        {
            _repository = repository;
            _logger = logger;
        }

        [HttpGet("")]
        public IActionResult Get()
        {
            var results = _repository.GetAllRoles();

            return Ok(Mapper.Map<IEnumerable<RoleViewModel>>(results));
        }

        [HttpPost("")]
        public async Task<IActionResult> Post([FromBody]RoleViewModel role)
        {
            if(ModelState.IsValid)
            {
                // Convert View Model to Model
                var newRole = Mapper.Map<Role>(role);

                _repository.AddRole(newRole);
                if(await _repository.SaveChangesAsync())
                {
                    return Created($"api/trips/{newRole.RoleName}", Mapper.Map<RoleViewModel>(newRole));
                }
                else
                {
                    return BadRequest("Failed to save changes");
                }
            }

            return BadRequest(ModelState);
        }
    }    
}

Controllers/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace KitKat.Controllers
{
    public class AppController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using KitKat.Models;
using KitKat.ViewModels;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace KitKat.Controllers
{
    public class AuthController : Controller
    {
        private SignInManager<KitKatUser> _signInManager;

        public AuthController(SignInManager<KitKatUser> signInManager)
        {
            _signInManager = signInManager;
        }

        public IActionResult Login()
        {
            if(User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Roles","Home");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel vm, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                var signInResult = await _signInManager.PasswordSignInAsync(vm.UserName, vm.Password, true, false);

                if (signInResult.Succeeded)
                {
                    if (string.IsNullOrWhiteSpace(returnUrl))
                    {
                        return RedirectToAction("Roles", "Home");
                    }
                    else
                    {
                        return Redirect(returnUrl);
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Username or password incorrect");
                }

            }

            return View();
        }

        public async Task<IActionResult> Logout()
        {
            if (User.Identity.IsAuthenticated)
            {
                await _signInManager.SignOutAsync();
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/Web/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using KitKat.Data;
using KitKat.Data.Contracts;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace KitKat.Controllers.Web
{
    public class HomeController : Controller
    {
        private IConfigurationRoot _config;
        private ILogger<HomeController> _logger;
        private IRoleRepository _repository;

        // private KitKatContext _context;

        public HomeController(IConfigurationRoot config ,
       //     KitKatContext context
                IRoleRepository repository,
                ILogger<HomeController> logger
            )
        {
            _config = config;
            _repository = repository;
            _logger = logger;
         //   _context = context;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            //   var data = _context.Roles.ToList();
            try
            {
                var data = _repository.GetAllRoles();

                return View(data);
            }
            catch(Exception ex)
            {
                _logger.LogError($"Failed to get roles : {ex.Message}");
                return Redirect("/error");
            }
        }

        [Authorize]
        public IActionResult Roles()
        {
            var data = _repository.GetAllRoles();

            return View(data);
        }
    }
}

Views/App/Index.cshtml
@{
    <h1>Index View</h1>
}

Views/Home/Index.cshtml
@model IEnumerable<KitKat.Models.Role>

@{
    <h1>Home View</h1>

    <ul>
        @foreach(var item in Model)
        {
            <li>@item.RoleName</li>

        }
    </ul>

    <div class="col-md-12">
       <a asp-controller="Home" asp-action="Roles" class="btn btn-lg btn-success">vIEW My Roles </a>        

    </div>
}

Views/Home/Roles.cshtml
@model IEnumerable<KitKat.Models.Role>

@{
    <h1>Roles View</h1>

    <ul>
        @foreach(var item in Model)
        {
            <li>@item.RoleName</li>

        }
    </ul>
}

Views/Shared/_BottomBar.cshtml
<div id="footer" class="container-fluid">
    <div class="navbar navbar-inverse navbar-fixed-bottom">
        <h4 class="text-center text-info">  &copy; 2016 Kit Kat </h4>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootswatch/yeti/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>        
    @Html.Partial("~/Views/Shared/_SideBar.cshtml")
    <div id="wrapper">
        <nav class="navbar-inverse">            
            @Html.Partial("~/Views/Shared/_TopBar.cshtml")
        </nav>
        <div id="main" class="container-fluid">
            <div>
                @RenderBody()
            </div>
        </div>
        @Html.Partial("~/Views/Shared/_BottomBar.cshtml")
    </div>
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"> </script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/js/site.js"></script>
    @RenderSection("scripts", false)
</body>
</html>

Views/Shared/_SideBar.cshtml
<div id="sidebar">
    @if (User.Identity.IsAuthenticated)
    {
    <img src="~/img/user1.jpg" alt="headshot" class="headshot" />
    <span id="username">@User.Identity.Name </span>
    }
    <ul class="nav">
        <li class="active"><a asp-controller="App" asp-action="Index">Home</a></li>
        <li><a asp-controller="App" asp-action="About">About</a></li>
        <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
        <li><a asp-controller="Auth" asp-action="Logout">Testing-SideBar</a></li>
        @if (User.Identity.IsAuthenticated)
        {
        <li><a asp-controller="App" asp-action="My Trips">About</a></li>
        <li><a asp-controller="Auth" asp-action="Logout">Logout</a></li>
       
        }
    </ul>
</div>

Views/Shared/_TopBar.cshtml
<div class="container-fluid">
    <ul class="nav navbar-nav navbar-left">
        <li>
            <button id="sidebarToggle" class="btn btn-primary">
                <i class="fa  fa-angle-left"></i>
            </button>
        </li>
    </ul>
    <a asp-controller="App" asp-action="Index" class="navbar-brand">Kit Kat </a>

    <ul class="nav navbar-nav navbar-right">

        <li>
            <a href="#" class="btn btn-sm btn-info">
                <i class="fa fa-save"></i> Save
            </a>
        </li>
        <li>
            <a href="#" class="btn btn-sm btn-info">
                <i class="fa fa-print"></i> Print
            </a>
        </li>

        <li class="dropdown">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Not Logged In <b class="caret"></b></a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                <li><a href="@Url.Action("Login", "Account")">Login</a></li>
                <li><a href="@Url.Action("Register", "Account")">Register</a></li>
                <li class="divider"></li>
                <li><a href="@Url.Action("ForgotPassword", "Account")">Forgot Password</a></li>
                <li class="divider"></li>
                <li><a href="@Url.Action("ForgotPassword", "Account")">Top Bar Testing</a></li>
            </ul>

        </li>

    </ul>
</div>